
apiVersion: v1
kind: Namespace
metadata:
  name: edison
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: edison
  name: weight-deployment
  labels:
    app: weight
spec:
  selector:
    matchLabels:
      app: weight
  replicas: 1
  template:
    metadata:
      labels:
        app: weight
    spec:
      containers:
      - name: weight
        image: europe-west2-docker.pkg.dev/edison-353618/tracker/weight:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: weight-service
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: edison
  name: weight-service
spec:
  selector:
    app: weight
  ports:
  - name: http
    port: 8080
    nodePort: 30080
  type: NodePort

